name: akt2
dependencies:
- python=3.6
- matplotlib
- jupyterlab
- tensorflow==2.0.0
- numpy
- scikit-image==0.15.0
- scikit-learn==0.21.3
- imageio==2.5.0
- keras
- python-chromedriver-binary
- tensorboard
- pip:
  - tensorflow-addons==0.5.2
  - imageio-ffmpeg==0.3.0
  - opencv-python==4.1.1.26
  - google-images-download==2.8.0

